### ISSUE TITLE
Decide exact program requirements

### ISSUE THREAD

**Issue by nay-su** [annazwicker/cat-partners#1]
Finalize features and requirements of Cat Partners application.

 - Finish Moscow method
 - what features are we going to implement?
 - what are we going to be making the app on?
 - what platform is it going to be on?
 - what kind of database are we going to use?

**Comment by nay-su** [comment]
completed first meeting with Cat Partner manager Kelly. We now have an updated Moscow list of requirements

**Comment by nay-su** [comment]
Completed user stories and use cases

**Comment by annazwicker** [comment]
Met with Kelly to determine the full list of requirements for our project.  This list can be found in the meeting notes in Google Drive, and a condensed version of the MOSCOW list can be found in the writing assignment 2 document.  In this meeting, Kelly gave us more insight into what she needed from the website as well as the priority of different features.  This meeting lasted about 35 minutes.

**Comment by nay-su** [comment]
Beginning research on Dart and Flutter

**Comment by nay-su** [comment]
- installed Flutter on computer
- https://docs.flutter.dev/get-started/install/windows/web <- this link instructs you on how to get started if you want to use Flutter for web development. I used the VScode extension to prepare the SDK
- dartpad exists as an online alternative https://dartpad.dev/? 
- Things I learned
   - Dart is very very to Java
   - Flutter has a lot of convenient autocomplete options  (control spacebar to access options) (use refractor tool)
   - Flutter has extensive documentation
   - Flutter apps are based on widgets -- they're a bit like xml elements. see widget tree
   - Learned Scaffolds are used to create visual designs
   - adding const to widget makes it immutable
   - properties are used to customize widgets. a property may take another widget as an argument

**Comment by nay-su** [comment]
beginning flutter studies again

**Comment by nay-su** [comment]
learned about
- containers (dart equivalent of divs)
- flex layouts (similar to js flexboxes)
- debugger
- widgets that account for states

**Comment by nay-su** [comment]
beginning to create relational database with Jayden

**Comment by nay-su** [comment]
- established google cloud database will be SQL
- created initial database schema

todo: 
- add types for every entry
- add tables

**Comment by nay-su** [comment]
beginning uml design. I'm doing a structural uml. Beginning research on how Flutter implements external databases so I can place it in an class diagram

**Comment by nay-su** [comment]
- confirmed Flutter IS object oriented
- need to understand how widgets fit into the object scheme
- found out there's a distinction between class diagrams and widget hierarchy that makes up the UI. Unsure how that fits into the assignment

**Comment by nay-su** [comment]
- concluded that a widget/html tree will have to be made eventually, but due to the specifications of the writing assignment, it will be safer to make a UML class diagram on the javascript aspects of the project website
- doing research on database usage in Flutter. Learned that database tables are typically assigned classes
- learned of the existence of the personal DataAccessLayer class and how it acts as an intermediary between Flutter widgets and the database

**Comment by nay-su** [comment]
- completed initial class UML, converting sql data types into DART ones and implementing the relevant methods. Currently, all fields and methods are assumed to be public because we don't know how exactly they're going to be implemented. If possible, the plan is to private them and to utilize more sophisticated getter, setter methods

**Comment by MMSU-1987** [comment]
Begun Flutter study 30 mins ago. Need to download Flutter and see how it works with Figma.

**Comment by MMSU-1987** [comment]
Download flutter for VScode. Had issues downloading it due to personal device. Will need to experiment with it and see how Figma works with it in the future.

**Comment by MMSU-1987** [comment]
Been looking into how flutter works. Also began brainstorming how mobile design would look like.

**Comment by MMSU-1987** [comment]
Got some very, very basic designs for mobile. Will finish the rest another time and show it to everyone when the topic arises.

**Comment by nay-su** [comment]
organizing plans, designs, and writing assignments within google drive for easier viewing

**Comment by nay-su** [comment]
- updating MOSCOW with additional requirements that were not realized until recently
  - additions to admin features
  - addition to export feature
  - change to note-taking feature. separated into notes for event and cat sightings
  - split notification to 2 parts: opt-in email notifications and default homescreen notifications
  - add admin notification for user information
  - added detail to export CSV feature: for feeder entry data, for cat sightings data, for user data
- bolded features in MOSCOW that weren't addressed in Figma design
