### ISSUE TITLE
General Group Meetings

### ISSUE THREAD

**Issue by annazwicker** [annazwicker/cat-partners#12]
Will post basic notes from meetings here as well as who all was present.

**Comment by annazwicker** [comment]
2/13/2024 Group Meeting
Spent the last 30 minutes of our meeting continuing to discuss Figma design and the writing assignment (sorting out who will complete which parts and selecting process models).  Also helped Marlon debug his environment.

Jayden, Marlon, and Anna were present for this portion of the meeting.  Daniel was here for the first half (from 7-7:30).  (1 hour total for the other three members).  Stopping work here.

**Comment by nay-su** [comment]
beginning group meeting about
- flutter environment
- Kelly's feedback about the prototype sent to her

**Comment by annazwicker** [comment]
2/20 general capstone meeting (7:00PM start, 8:00PM end)

- Worked on RCWS abstract 
- Worked through the various sections of the writing assignment
- Reviewed what happened in the meeting on 2/18 with Kelly 

Meeting Time: 60 minutes
Members: Marlon, Jayden, Daniel (only present 35 minutes), Anna

**Comment by annazwicker** [comment]
2/23 general capstone meeting (7:30pm start, 9:00pm end)

- Discussed goals for Tuesday 
- Reassigned tasks based on frontend vs. backend code 
- Worked on individual assignments

Meeting time: 90 minutes
Members: Marlon (only stayed one hour), Jayden, Daniel (only stayed one hour), Anna

**Comment by annazwicker** [comment]
2/27 general capstone meeting (7:00pm start, 8:00pm end)

- Discussed any progress made
- Discussed which database we plan to use
- Worked on first pull request/merge branch 

Meeting time: 60 minutes
Members: Marlon, Jayden, Daniel, Anna

**Comment by nay-su** [comment]
3/1 general capstone meeting (7:00 pm start, 7:20 pm end)
- progress report
- task assignment by next meeting

meeting time: 20 minutes
Members: Marlon, Jayden, Daniel

**Comment by nay-su** [comment]
3/5 general capstone meeting (7:00 pm start)

**Comment by annazwicker** [comment]
3/19 general capstone meeting (7:00pm start, 8:00pm end)

- Pull request and merge on Anna's code
- Work towards getting Marlon's code to pull request/merge ready state

Meeting time: 1 hour
Members: Daniel, Anna, Marlon

**Comment by MMSU-1987** [comment]
2/22 In-class meeting(9:30 AM start)
- Met at Anna's place
- Continued work

Members: Anna, Marlon

**Comment by annazwicker** [comment]
3/26 General capstone meeting (7:00pm start, 8:00pm end)

- Worked as a group to fix the main branch by adding the imports, for some reason Daniel's works but no one else's version of the main branch works.  Not completely set on a solution yet, but we will discuss it more in class tomorrow.

Members: Anna, Marlon, Jayden, Daniel

**Comment by nay-su** [comment]
4/2 General Capstone Meeting (7pm to 7:38pm)
- discussed technical features present in our project to incorporate into the poster
- assigned tasks



   - Anna
	by next tuesday
	admin page: edit accounts, edit admin capabilities, export data

Marlon
	by next Friday
	spend 2-3 hours figuring out Google sign in authentication. Flutter discprd


Daniel 
	by next Friday
	create working connection between site and Google Function
	Implement 


Jayden
	by next Friday

**Comment by annazwicker** [comment]
4/2 General capstone meeting (7:00pm start, 8:00pm end)

- Discussed feedback from Dr. Anthony and how to best proceed with the time we have remaining
- Laid out specific goals for each person to have done within the next week
- Worked to figure out what needs to be done as far as Google Account Integration
- Fixed Google Account integration ownership.

Members: Marlon, Jayden, Anna, Daniel

**Comment by MMSU-1987** [comment]
4/5 Meet up(7pm - 8pm)
Mainly just worked
- Daniel worked on Firebase
- Marlon did research on google sign up with Firebase and looked at account and about pages
- Jayden made progress on feeder

**Comment by annazwicker** [comment]
4/7 Extra capstone meeting (7:00pm start, 9:00pm end)

- Got the database connected with the website using a simple call
- Altered the account page to include a basic profile picture
- Fixed fonts and other formatting issues
- Primarily worked on the poster (editing formatting, fixing the text, adding screenshots, etc.)

Members: Jayden, Daniel, Anna, Marlon

**Comment by annazwicker** [comment]
4/9 General capstone meeting (7:00pm start, 8:15pm end)

- Finalized the poster designs
- Discussed how to format the edit admin users tab in the admin page

Members: Jayden, Anna, Marlon, Daniel

**Comment by annazwicker** [comment]
4/12 General capstone meeting (7:00pm start, 8:15pm end)

- Merged Daniel's code
- Anna fixed the separate files for the admin page
- Worked on merging Jayden's code
- Upgraded Jayden, Daniel, and Anna's Flutter

Members: Jayden, Anna, Daniel

**Comment by annazwicker** [comment]
4/15 Extra capstone meeting (8:30pm start, 9:00pm end)

- Discussed plans for who's talking about what for tomorrow's RCWS poster presentation
- Made plans as to what to do for the database and connecting it to the front end

Members: Jayden, Daniel, Anna, Marlon

**Comment by annazwicker** [comment]
4/16 General capstone meeting (7:00pm start, 8:00pm end)

- Marlon continued work on Google Account integration 
- Anna worked on creating the search users tab in the admin page
- Jayden worked on the feeder page

Members: Jayden, Anna, Marlon

**Comment by MMSU-1987** [comment]
4/19 General capstone meeting (7:00pm start, 8:00pm end)
We work on our own tasks
- Daniel: Database backend
- Marlon: General adjustments to pages(text align and rewording)
- Jayden: Feeder Sign in table
Members: Daniel, Marlon, Jayden

**Comment by annazwicker** [comment]
4/21 Extra capstone meeting (7:00pm start, 11:30pm end)

- Anna: edited all the text on the about page.  Worked on the presentation.  Worked with Daniel to figure out how to make the email field permanent and not changeable from the user's end.

Members: Daniel, Marlon, Anna, Jayden (didn't come until 10:30)

**Comment by annazwicker** [comment]
4/22 Extra capstone meeting (9:00pm start, 12:20 end)

- Revised the presentation's wording and formatting.
- Other various tasks, see the other GitHub issues for more detail.

Members: Anna, Daniel, Jayden, Marlon
