### ISSUE TITLE
Google Account Integration

### ISSUE THREAD

**Issue by JaydenBea** [annazwicker/cat-partners#19]
We're going to use Google Account integration for the website, enabling users to sign into our website via their Google Account. This issue is for researching and implementing the setup and connections required for it. It's likely that we can obtain information such as a user's name and email for use as well (name for displaying on schedule, email for email notifications about slots).

This seems to be Google main's page for it: [Integrating Google Sign-In into your web app](https://developers.google.com/identity/sign-in/web/sign-in)

**Comment by JaydenBea** [comment]
Startpost (7:20pm)

- Beginning research on how to do Google Account integration. This seems to be Google main's page for it: [Integrating Google Sign-In into your web app](\https://developers.google.com/identity/sign-in/web/sign-in)

**Comment by MMSU-1987** [comment]
Started looking into how to actually implement google sign in after working on Anna's request. Have checked out links beforehand, but will look into link provided Jayden.

**Comment by MMSU-1987** [comment]
Watched video(https://www.youtube.com/watch?v=Q00Foa8CiDk) and looked at Jayden's link. Thought it was simple.....it was not. Got an exception
![image](https://github.com/annazwicker/cat-partners/assets/110742858/6624cd64-e3a5-4796-b48e-fb26935f3eaa)

**Comment by MMSU-1987** [comment]
As said previously, not as simple as I thought, but i think the rest of the work needed for it to be done is the coding part. 
Regardless, I'm stopping work for now. Worked for ~2hrs(~1hr on Account page, ~1hr on google sign in).
Also, link provided by Jayden is not relevant due to web using a different package(linked here)
https://pub.dev/packages/google_sign_in_web
https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in/example/lib/main.dart

**Comment by MMSU-1987** [comment]
Starting work rn. Plan to start the code part of the google sign up

**Comment by MMSU-1987** [comment]
Almost forgot we are using firebase, so had to look into that as well. Laptop crashed after trying to get firebase dependency, which messed up pubsec.yaml file, so had to fix that.
https://medium.com/@dev.lens/flutter-google-sign-in-using-firebase-authentication-step-by-step-ef2ddfb84a2c

**Comment by MMSU-1987** [comment]
Stopped work for now. Worked for ~hr. Will learn more about Firebase from Daniel in the upcoming meeting. I think I understand the next step. It helps that the link previously shown had code for the google sign in and sign out, so it will be useful.

**Comment by MMSU-1987** [comment]
Stopping work for now(~hr). Added new file for google login(user_google.dart). It will likely need to be a parameter for other classes, so take that into account. 

Work for total of ~6 hrs(2hr meetings, 4hr personal time)

**Comment by MMSU-1987** [comment]
Started work. Will continue to work on google sign in. Need to find resources that use google_sign_in_web.

**Comment by MMSU-1987** [comment]
Finished file based on contents of this video(https://www.youtube.com/watch?v=PkvW5WoUonQ). Will now attempt to add google sign in by placing in the Navbar file in components

**Comment by MMSU-1987** [comment]
Currently creating new file for the login page structure

**Comment by MMSU-1987** [comment]
Almost finished login page. Will need to integrate into Nav bar

**Comment by MMSU-1987** [comment]
Stopping work for now(worked for ~2 hrs). Ran into some issues(device crashed while commiting on github desktop and now i cant access repository through github desktop). Will fix it.

**Comment by MMSU-1987** [comment]
Starting work. Plan to fix google sign in.

**Comment by MMSU-1987** [comment]
Stopping work for now(worked for ~1 hr). Sort of found the issue, and did find some potential solutions.
https://stackoverflow.com/questions/77705647/flutter-typeerror-class-constructor-indexeddblocalpersistence-cannot-be-invok

**Comment by MMSU-1987** [comment]
Started work. With google sign in fixed, I need to fixed the the format of it. Perhaps adding SU Cat Partners logo

**Comment by MMSU-1987** [comment]
Current progress of the layout. I'll add a box background for the button then move on to working on a different page.
![image](https://github.com/annazwicker/cat-partners/assets/110742858/f7d578ff-77a1-4882-b2b2-c958ef9ee634)

**Comment by MMSU-1987** [comment]
Will start work now. Will attempt to get all needed information for database on users and attempt to add it.

**Comment by MMSU-1987** [comment]
Found how to properly access each field of a user(name, email, etc.). Will attempt to add to database

**Comment by MMSU-1987** [comment]
Noticed potential issue of token not being the same. Need to figure that out

**Comment by MMSU-1987** [comment]
Stopped work for now.

Figured out token/ID thing. However, this causes issues when changing emails. Will need to mess with account page and google sign in to account for that

worked for 1hr 30 mins.

**Comment by MMSU-1987** [comment]
Forgot to make issue, but finally added database interactions. New users will be added to database. If email is changed, it will make necessary changes without creating a new user.

**Comment by nay-su** [comment]
all pages that require user specific info, except feeder page, now accepts the logged in user's info
