### ISSUE TITLE
Create login screen design (figma)

### ISSUE THREAD

**Issue by annazwicker** [annazwicker/cat-partners#2]
Create login screen:

This should have the following features:
- username/email field
- password field 
- new account field
- "keep me logged" in button

**Comment by nay-su** [comment]
watched Figma tutorial video

**Comment by nay-su** [comment]
beginning Figma design

**Comment by nay-su** [comment]
begin researching sign up through google feature. the current plan is to not have a separate login page but to implement a kind of popup box that makes signing up and logging in simple

**Comment by nay-su** [comment]
found relevant Google page on the one-tap feature: https://developers.google.com/identity/gsi/web/guides/offerings
- established that we can add a delete account feature within the website
- distinction between HTML and Javascript API
- learned that the sign up through Google feature button cannot be customized. will have to account for this in design
- "To enable Sign In With Google on your website, you first need to set up your Google API client ID" This may be problematic during the design and programming phase of this project where we don't have a physical site up yet. This is something we have to consider
- content security policy is optional
- requires being a Google API client using a Google API Project -- thankfully, this doesn't seem to be a very high investment, although how it affects permissions after we graduate remains to be seen
-
