### ISSUE TITLE
Create Admin Page 

### ISSUE THREAD

**Issue by annazwicker** [annazwicker/cat-partners#22]
Create the admin page according to the Figma designs found here: https://www.figma.com/file/GuXkK5D8kMGyrWSGBwqHgi/Screen-Designs?type=design&node-id=0-1&mode=design&t=b1MBz0s6BqNN3FfP-0

**Comment by annazwicker** [comment]
Starting work (6:53).  I'm going to start working on the admin page.  I think the best starting point will be how Marlon constructed the about page with tabs within a box.  I'm going to try to copy what he has in order to keep the formatting the same and then work to change it to fit the admin needs.

**Comment by annazwicker** [comment]
I haven't been able to get Marlon's code to work, not sure what's wrong but it's saying some of the variables aren't declared when I tried to copy it over.

**Comment by annazwicker** [comment]
I still don't know what's wrong.  I fixed some of the errors (some of the code didn't copy correctly and so some function definitions were missing).  Another error is with the canLaunchUrl and launchUrl, but those are located in a different file and I'm not sure how that file interacts with the about page.  Stopping work for now (1 hour).

**Comment by annazwicker** [comment]
Starting work (3:03).  Going to try and get some sort of tab view working for the admin page.  I'm going to try and model it after Marlon's code but I don't think it's possible to simply copy and paste and modify (or rather that would take a lot more work than it's worth).

**Comment by annazwicker** [comment]
I've been looking at this link (https://docs.flutter.dev/cookbook/design/tabs) trying to figure out exactly how tab views work.  Not much other progress to report on.

**Comment by annazwicker** [comment]
I'm running into problems with creating constructors and also some import errors.  I'm going to work to resolve these to see if I can get the page to run.

**Comment by annazwicker** [comment]
I haven't been able to resolve the issues with the constructors and import errors.  I'm looking at the following links for ideas on how to resolve them.  https://stackoverflow.com/questions/74770912/text-is-imported-from-both-platforms and https://stackoverflow.com/questions/72946680/error-couldnt-find-constructor-imagepickeroptions-imagepickeroptions-option.

**Comment by annazwicker** [comment]
I still haven't been able to resolve the issues.  I can talk with my team about it tomorrow or Tuesday, but I think this is something I just need a little more time on.  Stopping work for now (2 hours).

**Comment by annazwicker** [comment]
Starting work (7:25), going to continue where I left off, trying to resolve the issue with the constructors and imports.

**Comment by annazwicker** [comment]
I've dug around in this link about constructors (https://dart.dev/language/constructors) but I haven't found anything that's super helpful regarding the functions in this project.

**Comment by annazwicker** [comment]
Nothing new to report on.  I don't know what's wrong with the syntax for my constructors, I might need to reformat the functions to fix the problem, but I don't want to break the functions down just yet.  Stopping work for now (1 hour).

**Comment by annazwicker** [comment]
Starting work (4:25pm).  Going to start creating the body of the different tabs starting with the edit accounts page.

**Comment by annazwicker** [comment]
Working on building the edit accounts page.  I'm planning to create a section for adding accounts and a section for deleting accounts.  I'm creating a separate class that will be called in the larger widget build method to keep the code looking somewhat cleaner.

**Comment by annazwicker** [comment]
I've made progress on the edit accounts page.  There are fields where the portion for add and deleting accounts are on top of each other, but I want to figure out how to build them side by side.

**Comment by annazwicker** [comment]
I'm playing around with the formatting of the add account and delete account portions of the page.  The spacing looks off and I'm not sure why, something probably just needs to be wrapped in padding, I'm just not sure which thing to wrap.  I'll try adding padding in various places later to see if that makes a difference.  Stopping work for now (1.5 hours).

**Comment by annazwicker** [comment]
Starting work (12:55pm), going to see if I can add automatic alphabetization to the edit admin users dropdown box on the delete side.  I don't want to spend a ton of time on this though so if it doesn't work then I'll figure it out later.  After this I plan to spend time getting the front end done for the other tabs in the admin page.

**Comment by annazwicker** [comment]
Used this website to figure out how to sort.  https://api.flutter.dev/flutter/dart-core/List/sort.html.  Nothing different is displaying yet though... I'm not sure why.

**Comment by annazwicker** [comment]
I think the alphabetization is working.  Just committed the code for the first two tabs of the admin page (edit accounts, and edit admin users).  Next steps are to get the edit cats and feeding stations tabs complete.  I'm going to start with edit cats, but the two tabs should be relatively similar in setup to each other.

**Comment by annazwicker** [comment]
The edit cats page is actually pretty similar to the other pages, I don't think it needs too much work.  I'm almost done with the modifications and then the edit feeding stations page should be very similar.

**Comment by annazwicker** [comment]
Edit cats page is basically done, I'm going to review it and then commit.  The edit feeding stations page should be pretty similar, I'll start that after I commit.

**Comment by annazwicker** [comment]
The edit feeding stations page is good to go.  I've found a problem with the spacing on all the current pages except the edit accounts page.  I'm not sure why it's off, but I need to play around with it so it's uniform in the end.

**Comment by annazwicker** [comment]
I'm still not sure what the problem is as far as horizontal alignment, I think it might help to get some insight from Marlon tomorrow as he's also done a lot of front end work.  It's not a huge deal but it does look a little funny as is right now.  Stopping work for now (3 hours).

**Comment by nay-su** [comment]
fencepost (8:30pm - 10:30pm)
- created various backend methods for admin page operations (not tested yet)
- deleteAccount
- addAdmin
- removeAdmin
- addCat
- deleteCat
- addStation
- deleteStation
- searchUsers

**Comment by nay-su** [comment]
fencepost (11pm - 12:15 am)
- messed with searchUsers(String searchTerm) in admin page. Don't currently have it working

**Comment by nay-su** [comment]
fencepost (12:15- )
- confirmed addCat works
- confirmed deleteCat works
- confirmed addStation works
- confirmed deleteStation works
- made general changes to above methods so they accept strings of the document ID as arguments rather than DocumentReferences

**Comment by nay-su** [comment]
fencepost(8pm 8:36pm)
- finished adding remaining backend functionality

**Comment by annazwicker** [comment]
Started work at 10:06pm.  Added dialogue boxes to the first four tabs in the admin page that asks the user to confirm their choices before proceeding.  Next steps are to add dialogue boxes that display either success or failure of the action.

**Comment by annazwicker** [comment]
Created success/error dialogue boxes for the edit cats and edit admin users pages.  Needs to be done with the edit accounts and edit feeding stations tabs.

**Comment by annazwicker** [comment]
All dialogue boxes successfully created, resolved merge conflicts.  Need to make pull request.

**Comment by annazwicker** [comment]
Stopping work for now, completed the merge.  Also discussed who is going to present what slides.  (A little over 2 hours).

**Comment by nay-su** [comment]
adding descriptions section to add cat

**Comment by nay-su** [comment]
fencepost:
- added description. re-created send to database functionality that was missing for some reason

**Comment by nay-su** [comment]
making admin page dynamic

**Comment by nay-su** [comment]
fencepost:
- found error in delete cat that causes assertion failure on cancelling
```Another exception was thrown: Assertion failed: file:///C:/Users/a/Downloads/flutter/packages/flutter/lib/src/material/dropdown.dart:1619:15```

**Comment by nay-su** [comment]
Turning edit_admin_content into a streambuilder that takes a stream of all users with admin permissions

**Comment by nay-su** [comment]
fencepost:
- made delete admin dynamic

todo: make add admin work based on results of email field not document id

**Comment by nay-su** [comment]
fencepost (11:20 - 12:00):
- made add admin textbar work by inputting email rather than documentID

**Comment by nay-su** [comment]
fencepost(12:00 - 12:22):
- edit_accounts_content.dart: edit user email text field now actually accepts email rather than documentID
- admin edit accounts delete email textfield now accepts email rather than documentID
- admin delete feeding station dropdown is now dynamic

**Comment by nay-su** [comment]
TODO:
- get some way for admins to see full list of users or emails. Currently the admin needs to know the user's full email to look them up. Maybe just get them the full list of email,name pairs all users?
