### ISSUE TITLE
Setting Up Google Function

### ISSUE THREAD

**Issue by nay-su** [annazwicker/cat-partners#28]
#17 
Setting up Google function to connect Google Cloud mysql database to Flutter backend.

**Comment by nay-su** [comment]
fencepost:
- figured out what image urls are in the context of google cloud run ("refers to the location of the Docker container image that contains your application code, dependencies, and runtime environment")
- trying to access the code content of url images from google cloud shell
-

**Comment by nay-su** [comment]
fencepost:
- moving onto understanding node.js javascript code
- messing with the test functinality of cloud functions
- configured environmental variables for catparnters-func for easier and securer(?) connection to sql database through sockets

**Comment by nay-su** [comment]
continuing node.js, google function code study (class)

**Comment by nay-su** [comment]
fencepost (class):

studied up on
- types of cloud functions (http, event driven)
- google function framework entry points, request response format
- request, response format
- handling CORS
- https triggers

**Comment by nay-su** [comment]
continuing cloud functions coding reserach

**Comment by nay-su** [comment]
fencepost:
- learned about query parameters
- attempting to set up socket connection to database
  - currently running into issue where cloud run will not deploy correctly with the inclusion of 
  ```const mysql = require('promise-mysql');```

**Comment by nay-su** [comment]
attempting different tutorial for connecting function to sql database

**Comment by nay-su** [comment]
fencepost:
- attempted to change db password environmental variable
- swapped from node.js to python to better follow this tutorial
  - https://www.youtube.com/watch?v=6VnpvPpuXTE
- successfully accessed database from cloud function

**Comment by nay-su** [comment]
fencepost:
- deleted faulty functions
- began research on connection.cursor execute syntax used in pymysql

**Comment by nay-su** [comment]
Beginning research on establishing communication between Google function and website

**Comment by nay-su** [comment]
fencepost
- https://docs.flutter.dev/cookbook/networking/send-data

**Comment by MMSU-1987** [comment]
Seems to be extremely useful for google sign in integration. Need to figure out email issue since school emails will be non-existent soon.
https://medium.com/codebrew/flutter-google-sign-in-without-firebase-3680713966fb

**Comment by nay-su** [comment]
establishing connection between google function and website

**Comment by nay-su** [comment]
setting up cloudfunctions package

**Comment by nay-su** [comment]
fencepost:
- established google_sign_in to OAuth Client ID
- trying to undersand depreciated google sign in package

**Comment by nay-su** [comment]
messing with COR settings

**Comment by nay-su** [comment]
fencepost:
- confirmed that uri and request format from Flutter side is reaching the google function. Logs indicate that the function is run and "finished with status code: 200"
- ClientException: XMLHttpRequest error., uri=https://us-central1-catpartners.cloudfunctions.net/get-catpartner
- changed pre-flight and main request headers for function to no avail

**Comment by nay-su** [comment]
considering alternatives: Most Flutter-Google support seems to be focused on Firebase
