### ISSUE TITLE
Implement login through email feature

### ISSUE THREAD

**Issue by nay-su** [annazwicker/cat-partners#3]
- we know the sign in through Google option exists, but we still need to figure out if we can allow users to sign in through other emails
 - implement sign in through (g)mail account feature

**Comment by MMSU-1987** [comment]
Started 30 mins ago, creating the design on figma to show to Kelly. Need to figure out which figma page it should be on.

**Comment by MMSU-1987** [comment]
Added extra functionality to figma design. This is mainly meant for simulation purposes(to show to Kelly). Meant to show that signing in through google is an option for the website. Added additional login page state to help with that.
![image](https://github.com/annazwicker/cat-partners/assets/110742858/c72276fb-96d4-481f-a948-98c60b0bd9f4)
