### ISSUE TITLE
Create feeder entry page design

### ISSUE THREAD

**Issue by JaydenBea** [annazwicker/cat-partners#7]
The feeder entry page is where feeders will assign themselves to refill stations.

Features:
- Accessible only when user is logged in 
- Display of feeder schedule over the upcoming days
- Option to add an entry (upcoming/current day)
- Option to remove any of the user's entries (upcoming/current day)
- Option to remove other user's entries (admin only)
- Submit/confirm an entry add/removal
- Links back to main/account pages

**Comment by JaydenBea** [comment]
Started work on feeder entry page design in Figma

**Comment by JaydenBea** [comment]
Fencepost:
- Found a plug-in that creates tables. Might be useful for schedule portion, if it's not too limiting
- Started a design for the actual schedule table
- Planned: 'Submit' button, buttons to show more information about each station, which can appear on a sidebar.

**Comment by JaydenBea** [comment]
Fencepost: 
- Created/fixed the component for the site's top navigation bar, which now attaches to the top of frames nicely.
- Experimented more with a table option. The current plan is to use a Table Creator table for the date and assigned feeders, and a more stylized header for the stations.
Endpost

**Comment by nay-su** [comment]
completing Figma screen design of feeder entry page based on Jayden's existing design

**Comment by nay-su** [comment]
filled out unfinished table with comments explaining their behavior when clicked. 
TODO:
- complete Figma page designs for the feeder page when a time slot has been selected for the first time
- complete Figma page designs for the feeder page when a filled time slot has been selected to be edited
- decide how a user can add comments
- decide how users can confirm that they have fed the cats
- decide how a user can add sightings of cats
- decide when to start showing time slots (the start of the week?)
- decide how users can browse past and future dates

**Comment by JaydenBea** [comment]
Starting at 3:15pm (forgot goalpost).
Goal is to finish or at least make substantial progress on entry page by the end of the day. Specifically:
- Make basic table structure for entries, to get it out of the way; without in-built table functionality in Figma, making this won't be simple, and it's an unnecessary obstacle.
- Add scrolling functionality to entry sub-window
- Add sidebar, where user can submit
- Depth to page, for further entry-editing functionality (removal, adding a node, marking a sighting)

**Comment by JaydenBea** [comment]
Fencepost:
- Made a satisfactory-looking table.
  - One header row for the date column and station names, plus a bar above labelled "Stations"
  - Header columns with the date. One has simplified weekday name (E.g. "Mo", "Tu", "We", etc.) and the other has the month/day ("Feb/1").
- Frame encasing the table, about to figure out how to make this scroll on its own.
To-do:
- Sidebar with "submit"
- Selecting a cell (clicking it) highlights it, indicating the user's name will be posted to it upon hitting submit.
- Buttons + sub-pages for deleting existing entries and writing notes for entries.
- Buttons/sub-pages for sightings. Alternatively, sightings may be their own page.

**Comment by JaydenBea** [comment]
Fencepost:
- Schedule sub-window now has its own scroll. It doesn't look very smooth, but that might just be my mouse.
- Added a comment on Figma outlining, in more detail, what page should be able to do.
- Created sidebar frame, with prompts on what user can do (add/edit). Will start looking into adding prototyping functionality for an interactive sidebar, that responds to clicking on entry cells.
Break

**Comment by JaydenBea** [comment]
Started work at 7:50pm.
- Added a blank 'sightings' box underneath the scrolling schedule.
- Beginning research into prototype interactions; goal is to make clicking a cell open entry edit options.
- To avoid spending too much time messing with Figma, all possible entry options will be displayed on prototype.

**Comment by JaydenBea** [comment]
- Started a layout for editing a blank entry.
- Contains a space for the feeder's name (which is labelled 'none') 
- Contains a space for sightings; they will be moved here, and the 'sightings' box made earlier will be removed, allowing the schedule more space.

**Comment by JaydenBea** [comment]
- Completed layout for editing a blank entry.
- - Box for feeder's name, with a 'claim slot' button
- - Box for notes, which is empty.
- - Section for sightings. each cat has a portait, name, and checkbox, which is interactable.

**Comment by JaydenBea** [comment]
Endpost
- Found a resource that shows how to use variables to do remote variant-changes.
- Added variables for four modes of sidebar: blank (default), empty, user's entry, and other entry.
- Added a variant of table cell, so that value of sidebar can change depending on variant clicked.

**Comment by JaydenBea** [comment]
Nevermind-I-kept-working-on-it-post
- Added changes to 'other entry' variant of sidebar
  - placeholder "Some OtherGuy" text for name
  - placeholder notes text
- Added the 'your entry' variant 
  - placeholder "Your McName" in feeder name
  - placeholder text in notes section
- Added a "claim slot" button to sidebar
  - Yellow for empty entries, indicating user can click it
  - Grayed out for entries that aren't the user's
  - Red-orange with "unclaim slot" text for user's entries.
Planned:
- Change placeholder cells' variants in schedule so that some are empty, some are the user's, and some are "Other". 
- Add all prototype interactions to cell variants (interactions are on two out of three).
